In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [3]:
df=pd.read_csv("Salary_data.csv")
df.head(10)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0

In [14]:
x_lebel=df.iloc[ : ,0].values
y_lebel=df.iloc[ : ,1].values
x_lebel= x_lebel.reshape(-1,1)
y_lebel= y_lebel.reshape(-1,1)

In [15]:
training_x,testing_x,training_y,testing_y=train_test_split(x_lebel,y_lebel,test_size=0.2,random_state=0)
training_x

array([[ 9.6],
       [ 4. ],
       [ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [16]:
lin=LinearRegression()
lin.fit(training_x,training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
pred_y=lin.predict(testing_x)

In [23]:
pred_y[5]

array([107799.50275317])

In [25]:
testing_y[5]

array([109431.])