In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [3]:
df=pd.read_csv("Salary_data.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [32]:
x_lebel=df.iloc[ : ,0].values
y_lebel=df.iloc[ : ,1].values
x_lebel=x_lebel.reshape(-1,1)
y_lebel=y_lebel.reshape(-1,1)

In [62]:
trainingx,testingx,trainingy,testingy=train_test_split(x_lebel,y_lebel,test_size=0.3,random_state=0)
trainingx

array([[ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [49]:
l=LinearRegression()
l.fit(trainingx,trainingy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [50]:
pred_y=l.predict(testingx)
pred_x=l.predict(testingy)


In [61]:
pred_y[3]

array([63282.41035735])

In [63]:
testingy[3]

array([63218.])